# Generated by Django 4.2.30 on 2026-06-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='meeting_id',
            new_name='meeting',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='title',
        ),
    ]
