# Generated by Django 4.2.30 on 2026-06-08 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_alter_bot_provider'),
        ('summaries', '0002_rename_meeting_id_summary_meeting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='meeting',
        ),
        migrations.AddField(
            model_name='summary',
            name='bot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.bot'),
        ),
    ]
