"""
Django settings for meetpulse project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Django 4.2 compatibility patch with Python 3.14+ (Ref: Ticket #35844)
from django.template.context import BaseContext
from copy import copy as _copy
try:
    _copy(BaseContext())
except AttributeError:
    def _patched_copy(self):
        duplicate = BaseContext()
        duplicate.__class__ = self.__class__
        duplicate.__dict__ = _copy(self.__dict__)
        duplicate.dicts = self.dicts[:]     #type: ignore
        return duplicate
    BaseContext.__copy__ = _patched_copy

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY', os.getenv('DJANGO_SECRET'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

_allowed_hosts_env = os.getenv("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = _allowed_hosts_env.split(",") if _allowed_hosts_env else []
if DEBUG:
    ALLOWED_HOSTS = ["*"]  # Allow all hosts in development (e.g. cloudflare tunnel)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'apps.accounts',
    'apps.meetings',
    'apps.transcripts',
    'apps.summaries',
    'apps.core',
    'apps.recordings',
    'apps.bots',
    'apps.webhooks'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'meetpulse.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'meetpulse.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS configuration
import json
try:
    cors_env = os.getenv('ALLOW_CORS')
    if cors_env:
        if cors_env.strip().startswith('['):
            CORS_ALLOWED_ORIGINS = json.loads(cors_env)
        else:
            CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_env.split(',') if origin.strip()]
    else:
        CORS_ALLOWED_ORIGINS = ["http://localhost:3000"]
except Exception:
    CORS_ALLOWED_ORIGINS = ["http://localhost:3000"]

CORS_ALLOW_CREDENTIALS = True

BOT_PROVIDER="recall"
RECALL_API_KEY=os.getenv("RECALL_API_KEY")

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER":
        "apps.core.custom_exception_handler.custom_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.accounts.authentication.SupabaseAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

RECALL_VERIFICATION_SECRET = os.getenv("RECALL_VERIFICATION_SECRET")

# Supabase auth
SUPABASE_URL = os.getenv("SUPABASE_URL", "")

# ---------------------------------------------------------------------------
# Structured logging (see apps/core/utils/logger.py -> `applog`)
# JSON lines are written to logs/app.jsonl; view them with `manage.py logs`.
# ---------------------------------------------------------------------------
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)
APP_LOG_FILE = LOG_DIR / "app.jsonl"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "app_json": {
            "()": "apps.core.utils.log_format.JsonLineFormatter",
        },
        "app_console": {
            "()": "apps.core.utils.log_format.ConsoleFormatter",
        },
    },
    "handlers": {
        "app_console": {
            "class": "logging.StreamHandler",
            "formatter": "app_console",
        },
        "app_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(APP_LOG_FILE),
            "maxBytes": 10 * 1024 * 1024,  # 10 MB
            "backupCount": 5,
            "encoding": "utf-8",
            "formatter": "app_json",
        },
    },
    "loggers": {
        "app": {
            "handlers": ["app_console", "app_file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}