# Generated by Django 4.2.30 on 2026-06-08 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_alter_bot_provider'),
        ('recordings', '0003_alter_recording_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='meeting',
        ),
        migrations.AddField(
            model_name='recording',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.bot'),
        ),
        migrations.AddField(
            model_name='recording',
            name='id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
