# Generated by Django 4.2.30 on 2026-06-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0004_remove_recording_meeting_recording_bot_recording_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
