# Generated by Django 4.2.30 on 2026-06-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0005_alter_recording_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='recording_provider_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
