# Generated by Django 4.2.30 on 2026-06-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0006_recording_recording_provider_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='recording_provider_id',
            new_name='provider_media_id',
        ),
        migrations.AddField(
            model_name='recording',
            name='provider_recording_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
