# Generated by Django 4.2.30 on 2026-06-08 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0004_remove_recording_meeting_recording_bot_recording_id'),
        ('transcripts', '0002_rename_meeting_id_transcript_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='meeting',
        ),
        migrations.AddField(
            model_name='transcript',
            name='recording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recordings.recording'),
        ),
    ]
