# Generated by Django 4.2.30 on 2026-06-06 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('meeting_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='meetings.meeting')),
                ('provider', models.CharField(max_length=50)),
                ('provider_bot_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('joining_call', 'Joining Call'), ('in_waiting_room', 'In Waiting Room'), ('in_call_not_recording', 'In Call Not Recording'), ('recording_permission_allowed', 'Recording Permission Allowed'), ('recording_permission_denied', 'Recording Permission Denied'), ('in_call_recording', 'In Call Recording'), ('call_ended', 'Call Ended'), ('done', 'Done'), ('fatal', 'Fatal')], default='pending', max_length=30)),
                ('meeting_url', models.CharField(max_length=100)),
                ('joined_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
