# Generated by Django 4.2.30 on 2026-06-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_rename_meeting_id_bot_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
