# Generated by Django 4.2.30 on 2026-06-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_alter_bot_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='sub_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
