# Generated by Django 4.2.30 on 2026-06-08 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_meeting_user'),
        ('bots', '0004_bot_sub_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meetings.meeting'),
        ),
    ]
