# Generated by Django 4.2.30 on 2026-06-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_alter_bot_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='provider',
            field=models.CharField(choices=[('recall', 'Recall'), ('custom', 'Custom')], default='recall', max_length=50),
        ),
    ]
