# Generated by Django 4.2.30 on 2026-06-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
